<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 static\gltfModels\dice\scene.gltf
Author: macriciox (https://sketchfab.com/macriciox)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dice-6ee97010819742a8b8713605695ec703
Title: Dice
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('/gltfModels/dice/scene.gltf');

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<!-- rotation={[-Math.PI / 2, 0, 0]} -->
		<!-- rotation={[Math.PI / 2, 0, 0]} -->
		<!-- <T.Group scale={1}> -->
		<T.Group scale={0.5}>
			<T.Mesh
				geometry={gltf.nodes.defaultMaterial.geometry}
				material={gltf.materials.DefaultMaterial}
			/>
			<T.Mesh
				geometry={gltf.nodes.defaultMaterial_1.geometry}
				material={gltf.materials.DefaultMaterial}
			/>
			<T.Mesh
				geometry={gltf.nodes.defaultMaterial_2.geometry}
				material={gltf.materials.DefaultMaterial}
			/>
			<T.Mesh
				geometry={gltf.nodes.defaultMaterial_3.geometry}
				material={gltf.materials.DefaultMaterial}
			/>
			<T.Mesh
				geometry={gltf.nodes.defaultMaterial_4.geometry}
				material={gltf.materials.DefaultMaterial}
			/>
			<T.Mesh
				geometry={gltf.nodes.defaultMaterial_5.geometry}
				material={gltf.materials.DefaultMaterial}
			/>
			<T.Mesh
				geometry={gltf.nodes.defaultMaterial_6.geometry}
				material={gltf.materials.DefaultMaterial}
			/>
		</T.Group>
		<!-- </T.Group> -->
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
